version: "3"
services:
  discord-ip-updater:
    image: ghcr.io/anujdatar/discord-ip-updater
    container_name: discord-ip-updater
    restart: unless-stopped
    environment:
      - WEBHOOK_FILE=/run/secrets/webhook
      - TZ=America/New_York
      - RECORD_TYPE=AAAA
      - FREQUENCY=1
      - MESSAGE=Server IP updated to-
    secrets:
      - webhook

networks:
  default:
    driver: bridge
    enable_ipv6: true
    ipam:
      driver: default
      config:
        - subnet: fd00::/64

secrets:
  webhook:
    file: webhook.txt
